### ISSUE TITLE
Can't reproduce Imagenet accuracies

### ISSUE THREAD

**Issue by AuroMun** [hpi-xnor/BMXNet-v2-wiki#1]
I tried to run resnet18_v1 on Imagenet with the following parameters: 
--batch-size 128 --bits 1 --bits-a 1 --dataset imagenet --epochs 50 --gpus 0,1 --lr 0.001 --lr-factor 0.1 --optimizer adam --lr-steps 40,45 --model resnet18_v1 --initialization gaussian

from https://github.com/hpi-xnor/BMXNet-v2-wiki/blob/master/experiment/first_exps/0/details.md.  After 40 epochs my val accuracy's just 43.6%, as opposed to ~48% in the results page. What could be the issue here?

**Comment by Jopyth** [comment]
If you are still working on this: the code used for that experiment has changed a lot since then, so this might explain the difference. I am going to update the wiki with more recent and updated experiments, as well as more details soon.

**Comment by AuroMun** [comment]
That would be great! Also, it would be helpful if you could include what dataset pre-processing  was done for ImageNet before train.

**Comment by AuroMun** [comment]
any updates?

**Comment by Jopyth** [comment]
ImageNet preprocessing can be seen [here](https://github.com/hpi-xnor/BMXNet-v2-examples/blob/master/datasets/imagenet.py) and I updated the results, see [here](https://github.com/hpi-xnor/BMXNet-v2-wiki/blob/master/CurrentBestResults.md).
